

CIFAR10:   # name needs to be matched with dataset class name
  root: /home/hp/software/shao/data/cifar10/
  trainset_sample_ratio: 1.0  # for few shot learning
  seed: 1  # random seed for trainset sample
  download: True
  model_num: 3
  

CIFAR100:   # name needs to be matched with dataset class name
  root: /home/hp/software/shao/data/cifar100/
  trainset_sample_ratio: 1.0  # for few shot learning
  seed: 1  # random seed for trainset sample
  download: True
  model_num: 3